### ISSUE TITLE
hdfs HA does not work when an active namenode completely dies

### ISSUE THREAD

**Issue by macgyver603** [ryancole/node-webhdfs#14]
I discovered that when the active namenode process dies or the server the active namenode is living on dies completely, the HA functionality in this module will not be able to transition over to the standby namenode after HDFS is able to handle the loss and cleanly failover to the standby namenode.

[The check that triggers the namenode switch](https://github.com/ryancole/node-webhdfs/blob/62a7358b857550618717d940d3adbfacf02fa8b7/src/webhdfs.js#L45) in the `WebHDFSClient` will only ever be run if the namenode being queried returns a webhdfs response. In the scenarios of complete process or server failure, the result is a `request` error which will just throw an error in the program using the client. 

I have a fix and should have a PR sometime soon. There were two small, but notable changes needed to handle those failover scenarios:   

1. `WebHDFSClient` should switch namenodes in the event of both `ECONNREFUSED` and
`ENOTFOUND` request errors in addition to the webhdfs `StandbyException`.   
2. Since there is a very brief period between an active namenode crash and the standby namenode failover, an exponential backoff is needed to prevent `WebHDFSClient` from rapidly bouncing back and forth between the standby namenode and the dead active namenode and complicating the failover process.

**Comment by ryancole** [comment]
Thank you, @macgyver603. I don't actively use this module anymore, but perhaps @bamazap, who contributed a lot of recent patches, might also be able to assist reviewing your adjustments? Not sure if @bamazap still uses this module either - worth a ping, though.

**Comment by godber** [comment]
This might benefit from feedback from @jsnoble too since he worked in this area some time ago.

**Comment by ryancole** [comment]
Closed by #15

**Comment by ryancole** [comment]
Thank you for the patch, @macgyver603. I've drafted a new release, via github, and published `1.0.0` to [npm](https://www.npmjs.com/package/node-webhdfs/v/1.0.0). I added you as a contributor to the repository. There is an email confirmation step for you to take, I believe, before you're added.
