### ISSUE TITLE
Kerberos support for authentication

### ISSUE THREAD

**Issue by jimmiehansson** [ryancole/node-webhdfs#5]
Thanks for the contribution, I am curious if there is any plan to integrate authentication support against the WebHDFS API using Kerberos?

**Comment by maticrivo** [comment]
hi @jimmiehansson this has been here for quite some time, did you ever find a solution for kerberos authentication and webhdf api with nodejs?

**Comment by jimmiehansson** [comment]
Sorry, can't recall the solution for this. I'll close this out as it isn't active anymore, and no support was initiated. In case someone else has a common interest in it, they can just resurrect it.

**Comment by maticrivo** [comment]
Hi, so I actually found the solution..
You have to make the kerberos authentication yourself and get the kerberos token, I use the `krb5` node_module for that. 
And once you have the token you have to send it in the Authorization header

**Comment by maticrivo** [comment]
With that said, it’s worth mentioning that I ended up not using this webhdf module but create a wrapper of my own

**Comment by jimmiehansson** [comment]
Thanks for the update! :100:
